import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/shared/auth/AuthContext";

import { Inter, Poppins } from "next/font/google";


const poppins = Poppins({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});
export const metadata: Metadata = {
  title: "HoodFood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={poppins.variable} 

      >
         <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
